name: Python CI

on:
  push:
    branches: [ "main", "feature/*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt pytest-html>=3.2.0
    - name: Run tests with pytest
      run: |
        mkdir -p reports/assets/css
        REPORT_DATE=$(date '+%Y-%m-%d')
        pytest tests \
          --html=reports/pytest_report.html \
          --self-contained-html \
          --css=reports/assets/css/style.css \
          --metadata "Title" "QA Portfolio | $REPORT_DATE" \
          --metadata "Python" "$(python --version)" \
          --metadata "Environment" "GitHub Actions" \
          --metadata "Base URL" "${{ secrets.TARGET_URL || 'N/A' }}"
    - name: Upload test artifacts
      uses: actions/upload-artifact@v4
      with:
        name: test-artifacts
        path: |
          reports/pytest_report.html
          reports/assets/css/
        retention-days: 14