name: Python CI

on:
  push:
    branches: [ "main", "feature/*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  # Latest stable
    - name: Set up Python
      uses: actions/setup-python@v5  # Latest stable
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests with pytest
      run: |
        pytest tests --html=report.html
    - name: Upload test report
      uses: actions/upload-artifact@v4  # Latest stable
      with:
        name: pytest-html-report
        path: report.html
        retention-days: 7
        if-no-files-found: error