name: Python CI

on:
  push:
    branches: [ "main", "feature/*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests with pytest
      run: |
        mkdir -p reports/assets/css
        pytest tests \
          --html=reports/pytest_report.html \
          --self-contained-html \
          --css=reports/assets/css/style.css \
          --title="QA Portfolio | $(date '+%Y-%m-%d')" \
          --metadata "Python Version" "$(python --version)" \
          --metadata "Base URL" "${{ secrets.TARGET_URL }}"
    - name: Upload test artifacts
      uses: actions/upload-artifact@v4
      with:
        name: test-artifacts
        path: |
          reports/pytest_report.html
          reports/assets/css/style.css
        retention-days: 14